name: Build WEB

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.5'
    - run: |
        cd source
        flutter pub get
        flutter build web
        cp -R build/web/ ../
        git config --global user.name 'zulhijaya18'
        git config --global user.email '32.zulhijaya@gmail.com'
        git commit -am "Automated"
        git push

